name: user
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.1
  shared_preferences: ^2.2.3
  flutter_skeleton_ui: ^0.0.6
  get: ^4.6.6
  country_code_picker: ^3.0.0
  google_maps_flutter: ^2.7.0
  flutter_switch: ^0.3.2
  image_picker: ^1.1.2
  geolocator: ^12.0.0
  url_launcher: ^6.3.0
  #flutter_share: ^2.0.0
  date_picker_timeline: ^1.2.6
  jiffy: ^6.3.1
  connectivity_plus: ^6.0.3
  flutter_multi_formatter: ^2.12.8
  webview_flutter: ^4.8.0
  geocoding: ^3.0.0
  google_nav_bar: ^5.0.6
  flutter_widget_from_html: ^0.15.1
  flutter_otp_text_field: ^1.1.3+2
  badges: ^3.1.2
  change_app_package_name: ^1.2.0
  firebase_core: ^3.1.0
  firebase_messaging: ^15.0.1
  carousel_slider_plus: ^7.1.0
  cached_network_image: ^3.4.1
  flutter_local_notifications: ^18.0.1
  lints: ^3.0.0
  xml: ^6.5.0
  share_plus: ^11.1.0
  zo_animated_border: ^1.0.0
  rive: ^0.13.20

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/sliders/
    - assets/images/
    - assets/rive/

  fonts:
    - family: bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: semibold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf

    - family: medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

    - family: regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
