// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxybSC0yjBdUncTDEGpXxPUuBKqJt0-dw',
    appId: '1:917397990481:web:b7bdc9fef55664cd4d9c70',
    messagingSenderId: '917397990481',
    projectId: 'afrobelleza',
    authDomain: 'afrobelleza.firebaseapp.com',
    storageBucket: 'afrobelleza.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFC0MB29a8peek_EEaIV0kUNzGJLyplDc',
    appId: '1:917397990481:android:8874ee471d489d544d9c70',
    messagingSenderId: '917397990481',
    projectId: 'afrobelleza',
    storageBucket: 'afrobelleza.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVxLgUCUGf0X_cQIp1MqPGwQpDMsNN_g8',
    appId: '1:917397990481:ios:11f7942ecf1a8ee04d9c70',
    messagingSenderId: '917397990481',
    projectId: 'afrobelleza',
    storageBucket: 'afrobelleza.firebasestorage.app',
    iosBundleId: 'ios.afrobelleza.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVxLgUCUGf0X_cQIp1MqPGwQpDMsNN_g8',
    appId: '1:917397990481:ios:11f7942ecf1a8ee04d9c70',
    messagingSenderId: '917397990481',
    projectId: 'afrobelleza',
    storageBucket: 'afrobelleza.firebasestorage.app',
    iosBundleId: 'ios.afrobelleza.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxybSC0yjBdUncTDEGpXxPUuBKqJt0-dw',
    appId: '1:917397990481:web:55f9a532036de4384d9c70',
    messagingSenderId: '917397990481',
    projectId: 'afrobelleza',
    authDomain: 'afrobelleza.firebaseapp.com',
    storageBucket: 'afrobelleza.firebasestorage.app',
  );

}