// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyBu73UNyWTnswQ0EUQ6GVWtYZ6Dp6hdBwo",
      authDomain: "afro-belleza.firebaseapp.com",
      projectId: "afro-belleza",
      storageBucket: "afro-belleza.firebasestorage.app",
      messagingSenderId: "776611190911",
      appId: "1:776611190911:web:5545568237ec34eba1874a",
      measurementId: "G-V99Q8MKQY7"
  );

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: "AIzaSyBu73UNyWTnswQ0EUQ6GVWtYZ6Dp6hdBwo",
      authDomain: "afro-belleza.firebaseapp.com",
      projectId: "afro-belleza",
      storageBucket: "afro-belleza.firebasestorage.app",
      messagingSenderId: "776611190911",
      appId: "1:776611190911:android:4b1b9c4fe8ad0be2a1874a",
      measurementId: "G-V99Q8MKQY7"
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa5Nzkwem00XC1By9KPyzlrsQjeoAzz-g',
    appId: '1:1022022823127:ios:33e7d1863e9e4b43f3d492',
    messagingSenderId: '1022022823127',
    projectId: 'ultimate-salon-flutter',
    storageBucket: 'ultimate-salon-flutter.appspot.com',
    iosClientId: '1022022823127-fchj97baoac3hp1fv77oapku1tgjbvds.apps.googleusercontent.com',
    iosBundleId: 'io.initappz.ultimate.salon.owner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa5Nzkwem00XC1By9KPyzlrsQjeoAzz-g',
    appId: '1:1022022823127:ios:33e7d1863e9e4b43f3d492',
    messagingSenderId: '1022022823127',
    projectId: 'ultimate-salon-flutter',
    storageBucket: 'ultimate-salon-flutter.appspot.com',
    iosClientId: '1022022823127-fchj97baoac3hp1fv77oapku1tgjbvds.apps.googleusercontent.com',
    iosBundleId: 'io.initappz.ultimate.salon.owner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
      apiKey: "AIzaSyBu73UNyWTnswQ0EUQ6GVWtYZ6Dp6hdBwo",
      authDomain: "afro-belleza.firebaseapp.com",
      projectId: "afro-belleza",
      storageBucket: "afro-belleza.firebasestorage.app",
      messagingSenderId: "776611190911",
      appId: "1:776611190911:web:5545568237ec34eba1874a",
      measurementId: "G-V99Q8MKQY7"
  );
}
