/*
  Authors : initappz (Rahul Jograna)
  Website : https://initappz.com/
  App Name : Ultimate Salon Full App Flutter V3
  This App Template Source code is licensed as per the
  terms found in the Website https://initappz.com/license
  Copyright and Good Faith Purchasers © 2024-present initappz.
*/
import "package:get/get.dart";

class LocaleString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "en_US": {
          "We need to Internet Access": "We need to Internet Access",
          "agree": "agree",
          "Profile": "Profile",
          "Inbox": "Inbox",
          "Opps, Please Login or Register first!": "Opps, Please Login or Register first!",
          "Acount": "Acount",
          "Sign In / Sign Up": "Sign In / Sign Up",
          "Edit Profile": "Edit Profile",
          "Product Order": "Product Order",
          "Your Address": "Your Address",
          "Wallet": "Wallet",
          "Refer & Earn": "Refer & Earn",
          "Change Password": "Change Password",
          "Languages": "Languages",
          "Chats": "Chats",
          "Contact Us": "Contact Us",
          "Frequently Asked Questions": "Frequently Asked Questions",
          "Help": "Help",
          "Privacy Policy": "Privacy Policy",
          "Terms & Conditions": "Terms & Conditions",
          "About us": "About us",
          "About": "About",
          "Logout": "Logout",
          "Add New Card": "Add New Card",
          "Email Address": "Email Address",
          "Card Holder Name": "Card Holder Name",
          "Card Number": "Card Number",
          "CVV": "CVV",
          "MM/YY": "MM/YY",
          "ADD CARD": "ADD CARD",
          "Add Review to": "Add Review to",
          "Please rate the quality of service for the appointment you have got!": "Please rate the quality of service for the appointment you have got!",
          "Your comments and suggesstions help us improve the service quality better!": "Your comments and suggesstions help us improve the service quality better!",
          "Write Notes": "Write Notes",
          "Add Review": "Add Review",
          "Save": "Save",
          "Cancle": "Cancle",
          "Select Address": "Select Address",
          "Add Address": "Add Address",
          "Address": "Address",
          "Add New": "Add New",
          "All Categories": "All Categories",
          "Appointment Detail": "Appointment Detail",
          "Booking Date & Time": "Booking Date & Time",
          "Booking Date": "Booking Date",
          "Booking Time": "Booking Time",
          "Services": "Services",
          "Packages": "Packages",
          "Pricing": "Pricing",
          "Discount": "Discount",
          "Wallet Discount": "Wallet Discount",
          "Distance Cost": "Distance Cost",
          "Service Tax": "Service Tax",
          "Total": "Total",
          "Payment Method": "Payment Method",
          "Total Amount": "Total Amount",
          "Your Appoinments Status": "Your Appoinments Status",
          "Cancel": "Cancel",
          "Appointments History": "Appointments History",
          "New": "New",
          "Old": "Old",
          "Grand Total": "Grand Total",
          "Appointment at": "Appointment at",
          "No New Appointment Found!": "No New Appointment Found!",
          "No Past Appointment Found!": "No Past Appointment Found!",
          "Cart": "Cart",
          "Continue": "Continue",
          "Special Discount": "Special Discount",
          "OFF": "OFF",
          "Total Price": "Total Price",
          "Specialist": "Specialist",
          "Salon": "Salon",
          "and more": "and more",
          "No Data Found Near You!": "No Data Found Near You!",
          "Categories": "Categories",
          "Items": "Items",
          "Payments": "Payments",
          "No Data Found!": "No Data Found!",
          "Message...": "Message...",
          "Checkout": "Checkout",
          "min": "min",
          "Bill Details": "Bill Details",
          "item Total": "item Total",
          "Taxes & Charges": "Taxes & Charges",
          "To Pay": "To Pay",
          "Select Date & Time": "Select Date & Time",
          "Access Your": "Access Your",
          "Location": "Location",
          "USE CURRENT LOCATION": "USE CURRENT LOCATION",
          "CHOOSE LOCATION": "CHOOSE LOCATION",
          "Complaints": "Complaints",
          "Issue With": "Issue With",
          "Freelancer": "Freelancer",
          "Select Freelancer": "Select Freelancer",
          "Select product": "Select product",
          "Select service": "Select service",
          "Select package": "Select package",
          "Select Reason": "Select Reason",
          "Title": "Title",
          "Brief of your issue": "Brief of your issue",
          "Comments": "Comments",
          "Write something on issue": "Write something on issue",
          "Upload Image": "Upload Image",
          "Submit": "Submit",
          "Full Name": "Full Name",
          "Message": "Message",
          "Select Coupon": "Select Coupon",
          "Use coupon code": "Use coupon code",
          "Valid until": "Valid until",
          "Choose From": "Choose From",
          "camera": "camera",
          "Camera": "Camera",
          "gallery": "gallery",
          "Gallery": "Gallery",
          "First Name": "First Name",
          "Last Name": "Last Name",
          "Gender": "Gender",
          "Male": "Male",
          "Female": "Female",
          "Email": "Email",
          "Code": "Code",
          "Phone": "Phone",
          "Connection Failed": "Connection Failed",
          "Could not connect to network": "Could not connect to network",
          "Please check and try again": "Please check and try again",
          "retry": "retry",
          "Filters": "Filters",
          "Done": "Done",
          "Hairstyle": "Hairstyle",
          "Mackup": "Mackup",
          "Hair Styling": "Hair Styling",
          "Spa": "Spa",
          "Facial Mackup": "Facial Mackup",
          "Trim & Saving": "Trim & Saving",
          "Rating": "Rating",
          "4.0 Star": "4.0 Star",
          "Other": "Other",
          "Distance": "Distance",
          "Sort by": "Sort by",
          "Most Popular": "Most Popular",
          "Cost Low To High": "Cost Low To High",
          "Cost High To Low": "Cost High To Low",
          "Price": "Price",
          "Find Location": "Find Location",
          "Search location": "Search location",
          "Use My Current Location": "Use My Current Location",
          "Confirm Location": "Confirm Location",
          "Verify your phone number": "Verify your phone number",
          "success_verified": "success_verified",
          "Search salon, spa and barber": "Search salon, spa and barber",
          "Find and book best services": "Find and book best services",
          "Top Categories": "Top Categories",
          "View all": "View all",
          "Top Specialist": "Top Specialist",
          "Top Salon": "Top Salon",
          "Book": "Book",
          "Top Products": "Top Products",
          "ADD": "ADD",
          "Book Services": "Book Services",
          "Packages Details": "Packages Details",
          "Book Now": "Book Now",
          "Remove Package": "Remove Package",
          "Services Included": "Services Included",
          "Packages Name": "Packages Name",
          "Duration": "Duration",
          "Photos": "Photos",
          "Payment": "Payment",
          "Offers & Benefits": "Offers & Benefits",
          "Apply Coupon Code": "Apply Coupon Code",
          "Coupon Applied": "Coupon Applied",
          "Available Balance": "Available Balance",
          "Notes For Service": "Notes For Service",
          "Appoinments notes": "Appoinments notes",
          "item Discount": "item Discount",
          "Distance Charge": "Distance Charge",
          "Please Add Your Address": "Please Add Your Address",
          "Pay": "Pay",
          "Slots": "Slots",
          "Select Date": "Select Date",
          "No Slots Found": "No Slots Found",
          "Select Slots": "Select Slots",
          "Make Payment": "Make Payment",
          "Save Todo and Retrun to List": "Save Todo and Retrun to List",
          "Find Barbarshop Nearby !": "Find Barbarshop Nearby !",
          "Attractive Promotions !": "Attractive Promotions !",
          "Professional Specialist !": "Professional Specialist !",
          "Get Specialist at your door steps !": "Get Specialist at your door steps !",
          "Buy from trusted professional !": "Buy from trusted professional !",
          "Skip": "Skip",
          "Next": "Next",
          "Previous": "Previous",
          "Get Started": "Get Started",
          "English": "English",
          "Hindi": "French",
          "French": "French",
          "Spanish": "Spanish",
          "Password": "Password",
          "Forgot Password ?": "Forgot Password ?",
          "Log In": "Log In",
          "Don\"t have account ?": "Don\"t have account ?",
          "Sign Up": "Sign Up",
          "Mobile Number": "Mobile Number",
          "Add New Address": "Add New Address",
          "House / Flat No.": "House / Flat No.",
          "Landmark": "Landmark",
          "Pincode": "Pincode",
          "Save Address": "Save Address",
          "Home": "Home",
          "Work": "Work",
          "Update": "Update",
          "Service at": "Service at",
          "At Home": "At Home",
          "At Salon": "At Salon",
          "Order Detail": "Order Detail",
          "Order At": "Order At",
          "Orders": "Orders",
          "X": "X",
          "Your Order Status": "Your Order Status",
          "Order History": "Order History",
          "Order Id": "Order Id",
          "No New Orders Found!": "No New Orders Found!",
          "No Past Orders Found!": "No Past Orders Found!",
          "Add Notes": "Add Notes",
          "Appoinments notes..": "Appoinments notes..",
          "Pay With Stripe": "Pay With Stripe",
          "Expiry": "Expiry",
          "Products Details": "Products Details",
          "Add To Cart": "Add To Cart",
          "Sold By": "Sold By",
          "Categories Info": "Categories Info",
          "Sub Categories Info": "Sub Categories Info",
          "Descriptions": "Descriptions",
          "Special Price": "Special Price",
          "Off": "Off",
          "Only 5 Days Left": "Only 5 Days Left",
          "Disclaimer": "Disclaimer",
          "Related Products": "Related Products",
          "Reviews": "Reviews",
          "Write your review": "Write your review",
          "Leave your experience..": "Leave your experience..",
          "post": "post",
          "Kevin Doyle": "Kevin Doyle",
          "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters":
              "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters",
          "Products": "Products",
          "Sort By": "Sort By",
          "Invite Now": "Invite Now",
          "Create an Account": "Create an Account",
          "Referral Code": "Referral Code",
          "By continuing, you agree to our": "By continuing, you agree to our",
          "Terms of Service": "Terms of Service",
          "You have already account ?": "You have already account ?",
          "Reset Password": "Reset Password",
          "Enter your email address or phone number and we will send a verification code to generate a new password": "Enter your email address or phone number and we will send a verification code to generate a new password",
          "Send OTP": "Send OTP",
          "Generate New Password": "Generate New Password",
          "New Password": "New Password",
          "Confirm Password": "Confirm Password",
          "Update Password": "Update Password",
          "Your Location": "Your Location",
          "Search For Salon, Services.....": "Search For Salon, Services.....",
          "Salons": "Salons",
          "KM": "KM",
          "OPEN": "OPEN",
          "Website": "Website",
          "Call": "Call",
          "Chat": "Chat",
          "Direction": "Direction",
          "Share": "Share",
          "Salon Specialist": "Salon Specialist",
          "Opening Hour": "Opening Hour",
          "Get Direction": "Get Direction",
          "Type": "Type",
          "View": "View",
          "Appointment": "Appointment",
          "Select Specialist": "Select Specialist",
          "Portfolio": "Portfolio",
          "Basic Info": "Basic Info",
          "No Internet Connection": "No Internet Connection",
          "Developed By": "Developed By",
          "NearBy": "NearBy",
          "Shop": "Shop",
          "Appoinment": "Appoinment",
          "Account": "Account",
          "Top Packages & Offers": "Top Packages & Offers",
          "Ms.Jolly Jonthon": "Ms.Jolly Jonthon",
          "Aromatherapy": "Aromatherapy",
          "Fee start from": "Fee start from",
          "All Transactions": "All Transactions",
          "Book an Appointment for Salon, Spa & Barber": "Book an Appointment for Salon, Spa & Barber",
          "Connect with Google": "Connect with Google",
          "Connect with Facebook": "Connect with Facebook",
          "Already have an account?": "Already have an account?",
          "Please wait": "Please wait",
          "All fields are required": "All fields are required",
          "Card Information Saved": "Card Information Saved",
          "Please add comments": "Please add comments",
          "Review Saved": "Review Saved",
          "Others": "Others",
          "item remove successfully": "item remove successfully",
          "NA": "NA",
          "COD": "COD",
          "Stripe": "Stripe",
          "PayPal": "PayPal",
          "Paytm": "Paytm",
          "Razorpay": "Razorpay",
          "Instamojo": "Instamojo",
          "Paystack": "Paystack",
          "Flutterwave": "Flutterwave",
          "Accepted": "Accepted",
          "Rejected by Freelancer": "Rejected by Freelancer",
          "Ongoing": "Ongoing",
          "Completed": "Completed",
          "Cancelled": "Cancelled",
          "Refunded": "Refunded",
          "Delayed": "Delayed",
          "Panding Payment": "Panding Payment",
          "Status Updated": "Status Updated",
          "Rate Your Appointment": "Rate Your Appointment",
          "Owner": "Owner",
          "Could not launch": "Could not launch",
          "Choose": "Choose",
          "Featching Location": "Featching Location",
          "The product arrived too late": "The product arrived too late",
          "The product did not match the description": "The product did not match the description",
          "The purchase was fraudulent": "The purchase was fraudulent",
          "The product was damaged or defective": "The product was damaged or defective",
          "The merchant shipped the wrong item": "The merchant shipped the wrong item",
          "Wrong Item Size or Wrong Product Shipped": "Wrong Item Size or Wrong Product Shipped",
          "Driver arrived too late": "Driver arrived too late",
          "Driver behavior": "Driver behavior",
          "Freelacer behavior": "Freelacer behavior",
          "Issue with Payment Amount": "Issue with Payment Amount",
          "Freelancer was fraudulent": "Freelancer was fraudulent",
          "Related to service": "Related to service",
          "Satisfaction of services": "Satisfaction of services",
          "Choose Issue With": "Choose Issue With",
          "Choose Reason": "Choose Reason",
          "Choose Service": "Choose Service",
          "Choose Package": "Choose Package",
          "Choose Product": "Choose Product",
          "Complaints registered": "Complaints registered",
          "New Mail Request Received": "New Mail Request Received",
          "You have received new mail": "You have received new mail",
          "New Contact Details": "New Contact Details",
          "We have received your request, we will respond on your issue soon": "We have received your request, we will respond on your issue soon",
          "Alert!": "Alert!",
          "Contact Information Sent": "Contact Information Sent",
          "Okay": "Okay",
          "Location services are disabled": "Location services are disabled",
          "Location permissions are permanently denied, we cannot request permissions": "Location permissions are permanently denied, we cannot request permissions",
          "We already have product with other freelancer": "We already have product with other freelancer",
          "We already have service or package with other salon or with freelancer": "We already have service or package with other salon or with freelancer",
          "Sorry we deliver the order near to": "Sorry we deliver the order near to",
          "Appoinments once placed cannot be cancelled and non-refundable": "Appoinments once placed cannot be cancelled and non-refundable",
          "Are you sure": "Are you sure",
          "Thank You!": "Thank You!",
          "For Your Appoinment": "For Your Appoinment",
          "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout":
              "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout",
          "TRACK MY APPOINTMENT": "TRACK MY APPOINTMENT",
          "BACK TO HOME": "BACK TO HOME",
          "Sunday": "Sunday",
          "Monday": "Monday",
          "Tuesday": "Tuesday",
          "Wednesday": "Wednesday",
          "Thursday": "Thursday",
          "Friday": "Friday",
          "Saturday": "Saturday",
          "Please select Slots": "Please select Slots",
          "Email is not valid": "Email is not valid",
          "Access denied": "Access denied",
          "error": "error",
          "Phone Number is required": "Phone Number is required",
          "Something went wrong while signup": "Something went wrong while signup",
          "Something went wrong": "Something went wrong",
          "Verification": "Verification",
          "We have sent verification code on": "We have sent verification code on",
          "Verify": "Verify",
          "Successfully Added": "Successfully Added",
          "Successfully Updated": "Successfully Updated",
          "Please select payment method": "Please select payment method",
          "We have already select product with other freelancer": "We have already select product with other freelancer",
          "Share with buddies": "Share with buddies",
          "Copied to clipboard": "Copied to clipboard",
          "Hey Buddy download": "Hey Buddy download",
          "Your friend": "Your friend",
          "has invited you to": "has invited you to",
          "from app store and use my code": "from app store and use my code",
          "while sign up we both will get": "while sign up we both will get",
          "wallet amount": "wallet amount",
          "Password mismatch": "Password mismatch",
          "No Website Found": "No Website Found",
          "Please checkout this salon": "Please checkout this salon",
          "Share with": "Share with",
          "Please select specialist": "Please select specialist",
          "Yes, Place Order": "Yes, Place Order",
          "Please select card": "Please select card",
          "Creating Order": "Creating Order",
          "TRACK MY ORDERS": "TRACK MY ORDERS",
          "For Your Orders": "For Your Orders",
          "Order notes..": "Order notes.."
        },
  "hi_IN":{
  "We need to Internet Access": "Nous avons besoin de Connexion Internet",
  "agree": "accepter",
  "Profile": "Profil",
  "Inbox": "Boîte de réception",
  "Opps, Please Login or Register first!": "Opps, veuillez vous connecter ou vous inscrire !",
  "Acount": "Compte",
  "Sign In / Sign Up": "Se connecter / S'inscrire",
  "Edit Profile": "Modifier le profil",
  "Product Order": "Commande de produits",
  "Your Address": "Votre adresse",
  "Wallet": "Portefeuille",
  "Refer & Earn": "Parrainez et gagnez",
  "Change Password": "Changer le mot de passe",
  "Languages": "Langues",
  "Chats": "Discussions",
  "Contact Us": "Contactez-nous",
  "Frequently Asked Questions": "Foire aux questions",
  "Help": "Aide",
  "Privacy Policy": "politique de confidentialité",
  "Terms & Conditions": "Conditions générales",
  "About us": "À propos de nous",
  "About": "À propos",
  "Logout": "Déconnexion",
  "Add New Card": "Ajouter une nouvelle carte",
  "Email Address": "Adresse email",
  "Card Holder Name": "Nom du titulaire de la carte",
  "Card Number": "Numéro de carte",
  "CVV": "CVV",
  "MM/YY": "MM/AA",
  "ADD CARD": "AJOUTER UNE CARTE",
  "Add Review to": "Ajouter un avis à",
  "Please rate the quality of service for the appointment you have got!": "Veuillez évaluer la qualité du service pour le rendez-vous que vous avez obtenu !",
  "Your comments and suggestions help us improve the service quality better!": "Vos commentaires et suggestions nous aident à améliorer la qualité du service !",
  "Write Notes": "Écrire des notes",
  "Add Review": "Ajouter un avis",
  "Save": "Sauvegarder",
  "Cancel": "Annuler",
  "Select Address": "Sélectionner l'adresse",
  "Add Address": "Ajouter une adresse",
  "Address": "Adresse",
  "Add New": "Ajouter un nouveau",
  "All Categories": "Toutes les catégories",
  "Appointment Detail": "Détail du rendez-vous",
  "Booking Date & Time": "Date et heure de réservation",
  "Booking Date": "Date de réservation",
  "Booking Time": "Heure de réservation",
  "Services": "Services",
  "Packages": "Forfaits",
  "Pricing": "Tarifs",
  "Discount": "Rabais",
  "Wallet Discount": "Remise sur le portefeuille",
  "Distance Cost": "Coût de distance",
  "Service Tax": "Taxe sur les services",
  "Total": "Total",
  "Payment Method": "Mode de paiement",
  "Total Amount": "Montant total",
  "Your Appointments Status": "Statut de vos rendez-vous",
  "Appointments History": "Historique des rendez-vous",
  "New": "Nouveau",
  "Old": "Vieux",
  "Grand Total": "Total",
  "Appointment at": "Rendez-vous à",
  "No New Appointment Found!": "Aucun nouveau rendez-vous trouvé !",
  "No Past Appointment Found!": "Aucun rendez-vous antérieur trouvé !",
  "Cart": "Chariot",
  "Continue": "Continuer",
  "Special Discount": "Remise spéciale",
  "OFF": "DÉSACTIVÉ",
  "Total Price": "Prix total",
  "Specialist": "Spécialiste",
  "Salon": "Salon",
  "and more": "et plus",
  "No Data Found Near You!": "Aucune donnée trouvée près de chez vous !",
  "Categories": "Catégories",
  "Items": "Articles",
  "Payments": "Paiements",
  "No Data Found!": "Aucune donnée trouvée !",
  "Message...": "Message...",
  "Checkout": "Vérifier",
  "min": "min",
  "Bill Details": "Détails de la facture",
  "item Total": "article Total",
  "Taxes & Charges": "Taxes et frais",
  "To Pay": "Payer",
  "Select Date & Time": "Sélectionner la date et l'heure",
  "Access Your": "Accédez à votre",
  "Location": "Emplacement",
  "USE CURRENT LOCATION": "UTILISER L'EMPLACEMENT ACTUEL",
  "CHOOSE LOCATION": "CHOISISSEZ L'EMPLACEMENT",
  "Complaints": "Plaintes",
  "Issue With": "Problème avec",
  "Freelancer": "Freelance",
  "Select Freelancer": "Sélectionner un freelance",
  "Select product": "Sélectionner un produit",
  "Select service": "Sélectionner un service",
  "Select package": "Sélectionner le forfait",
  "Select Reason": "Sélectionner la raison",
  "Title": "Titre",
  "Brief of your issue": "Bref de votre problématique",
  "Comments": "Commentaires",
  "Write something on issue": "Écrivez quelque chose sur le problème",
  "Upload Image": "Télécharger une image",
  "Submit": "Soumettre",
  "Full Name": "Nom et prénom",
  "Message": "Message",
  "Select Coupon": "Sélectionner le coupon",
  "Use coupon code": "Utiliser le code promo",
  "Valid until": "Valable jusqu'à",
  "Choose From": "Choisir parmi",
  "camera": "caméra",
  "Camera": "Caméra",
  "gallery": "galerie",
  "Gallery": "Galerie",
  "First Name": "Prénom",
  "Last Name": "Nom de famille",
  "Gender": "Genre",
  "Male": "Homme",
  "Female": "Femme",
  "Email": "E-mail",
  "Code": "Code",
  "Phone": "Téléphone",
  "Connection Failed": "Échec de la connexion",
  "Could not connect to network": "Impossible de se connecter au réseau",
  "Please check and try again": "Veuillez vérifier et réessayer",
  "retry": "réessayer",
  "Filters": "Filtres",
  "Done": "Fait",
  "Hairstyle": "Coiffure",
  "Mackup": "Mackup",
  "Hair Styling": "Coiffure",
  "Spa": "Spa",
  "Facial Mackup": "Maquillage facial",
  "Trim & Saving": "Découper et sauvegarder",
  "Rating": "Notation",
  "4.0 Star": "4.0 Étoiles",
  "Other": "Autre",
  "Distance": "Distance",
  "Sort by": "Trier par",
  "Most Popular": "Le plus populaire",
  "Cost Low To High": "Coût faible à élevé",
  "Cost High To Low": "Coût élevé à faible",
  "Price": "Prix",
  "Find Location": "Trouver un emplacement",
  "Search location": "Rechercher un emplacement",
  "Use My Current Location": "Utiliser ma position actuelle",
  "Confirm Location": "Confirmer l'emplacement",
  "Verify your phone number": "Vérifiez votre numéro de téléphone",
  "success_verified": "succès_vérifié",
  "Search salon, spa and barber": "Recherche salon, spa et barbier",
  "Find and book best services": "Réserver vos services Afro",
  "Top Categories": "Top catégories",
  "View all": "Voir tout",
  "Top Specialist": "Top Spécialiste",
  "Top Salon": "Meilleurs Salons",
  "Book": "Reserver",
  "Top Products": "Meilleurs produits",
  "ADD": "AJOUTER",
  "Book Services": "Services de livres",
  "Packages Details": "Détails des forfaits",
  "Book Now": "Réservez maintenant",
  "Remove Package": "Supprimer le paquet",
  "Services Included": "Prestations incluses",
  "Packages Name": "Nom des packages",
  "Duration": "Durée",
  "Photos": "Photos",
  "Payment": "Paiement",
  "Offers & Benefits": "Offres & Avantages",
  "Apply Coupon Code": "Appliquer le code promo",
  "Coupon Applied": "Coupon appliqué",
  "Available Balance": "Solde disponible",
  "Notes For Service": "Remarques concernant le service",
  "Appointments notes": "Notes de rendez-vous",
  "item Discount": "Remise sur l'article",
  "Distance Charge": "Frais de déplacement",
  "Please Add Your Address": "Veuillez ajouter votre adresse",
  "Pay": "Payer",
  "Slots": "Machines à sous",
  "Select Date": "Sélectionner une date",
  "No Slots Found": "Aucun emplacement trouvé",
  "Select Slots": "Sélectionner les emplacements",
  "Make Payment": "Effectuer le paiement",
  "Save Todo and Return to List": "Enregistrer Todo et revenir à la liste",
  "Find Barbershop Nearby!": "Trouvez Barbershop à proximité !",
  "Attractive Promotions!": "Des promotions attractives !",
  "Professional Specialist!": "Spécialiste professionnel !",
  "Get Specialist at your door steps!": "Obtenez un spécialiste à votre porte !",
  "Buy from trusted professional!": "Achetez auprès d'un professionnel de confiance !",
  "Skip": "Sauter",
  "Next": "Suivant",
  "Previous": "Précédent",
  "Get Started": "Commencer",
  "English": "Anglais",
  "French": "Français",
  "Spanish": "Espagnol",
  "Password": "Mot de passe",
  "Forgot Password?": "Mot de passe oublié ?",
  "Log In": "Se connecter",
  "Don't have account?": "Vous n'avez pas de compte ?",
  "Sign Up": "S'inscrire",
  "Mobile Number": "Numéro de portable",
  "Add New Address": "Ajouter une nouvelle adresse",
  "House / Flat No.": "Maison / Appartement N°",
  "Landmark": "Point de repère",
  "Pincode": "Code PIN",
  "Save Address": "Enregistrer l'adresse",
  "Home": "Maison",
  "Work": "Travail",
  "Update": "Mise à jour",
  "Service at": "Service à",
  "At Home": "À la maison",
  "At Salon": "Au Salon",
  "Order Detail": "Détail de la commande",
  "Order At": "Commander à",
  "Orders": "Ordres",
  "X": "X",
  "Your Order Status": "Statut de votre commande",
  "Order History": "Historique des commandes",
  "Order Id": "Numéro de commande",
  "No New Orders Found!": "Aucune nouvelle commande trouvée !",
  "No Past Orders Found!": "Aucune commande passée trouvée !",
  "Add Notes": "Ajouter des notes",
  "Appointments notes..": "Notes de rendez-vous..",
  "Pay With Stripe": "Payer avec Stripe",
  "Expiry": "Expiration",
  "Products Details": "Détails des produits",
  "Add To Cart": "Ajouter au panier",
  "Sold By": "Vendu par",
  "Categories Info": "Informations sur les catégories",
  "Sub Categories Info": "Informations sur les sous-catégories",
  "Descriptions": "Descriptions",
  "Special Price": "Prix spécial",
  "Off": "Désactivé",
  "Only 5 Days Left": "Il ne reste que 5 jours",
  "Disclaimer": "Clause de non-responsabilité",
  "Related Products": "Produits associés",
  "Reviews": "Commentaires",
  "Write your review": "Écrivez votre avis",
  "Leave your experience..": "Laissez votre expérience..",
  "post": "poste",
  "Kevin Doyle": "Kévin Doyle",
  "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters:": "C'est un fait bien établi qu'un lecteur sera distrait par le contenu lisible d'une page en examinant sa mise en page. L'intérêt d'utiliser Lorem Ipsum est qu'il a une distribution de lettres plus ou moins normale :",
  "\"\"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters\"\",": "\"\"C'est un fait bien établi qu'un lecteur sera distrait par le contenu lisible d'une page en examinant sa mise en page. L'intérêt d'utiliser Lorem Ipsum est qu'il a une distribution de lettres plus ou moins normale\"\",",
  "Products": "Produits",
  "Sort By": "Trier par",
  "Invite Now": "Inviter maintenant",
  "Create an Account": "Créer un compte",
  "Referral Code": "Code de référence",
  "By continuing, you agree to our": "En continuant, vous acceptez notre",
  "Terms of Service": "Conditions d'utilisation",
  "You have already account ?": "Vous avez déjà un compte ?",
  "Reset Password": "Réinitialiser le mot de passe",
  "Enter your email address or phone number and we will send a verification code to generate a new password": "Entrez votre adresse e-mail ou votre numéro de téléphone et nous vous enverrons un code de vérification pour générer un nouveau mot de passe",
  "Send OTP": "Envoyer OTP",
  "Generate New Password": "Générer un nouveau mot de passe",
  "New Password": "Nouveau mot de passe",
  "Confirm Password": "Confirmez le mot de passe",
  "Update Password": "Mettre à jour le mot de passe",
  "Your Location": "Votre emplacement",
  "Search For Salon, Services.....": "Recherche de salon, services.....",
  "Salons": "Salons",
  "KM": "KM",
  "OPEN": "Ouvert",
  "Website": "Site web",
  "Call": "Appel",
  "Chat": "Chat",
  "Direction": "Direction",
  "Share": "Partager",
  "Salon Specialist": "Spécialiste des salons",
  "Opening Hour": "Heure d'ouverture",
  "Get Direction": "Obtenir une direction",
  "Type": "Type",
  "View": "Voir",
  "Appointment": "Rendez-vous",
  "Select Specialist": "Sélectionner un spécialiste",
  "Portfolio": "Portefeuille",
  "Basic Info": "Informations de base",
  "No Internet Connection": "Pas de connexion Internet",
  "Developed By": "Développé par",
  "NearBy": "Proche",
  "Shop": "Boutique",
  "Account": "Compte",
  "Top Packages & Offers": "Meilleurs forfaits et offres",
  "Ms.Jolly Jonthon": "Mme Jolly Jonthon",
  "Aromatherapy": "Aromathérapie",
  "Fee start from": "Les frais commencent à partir de",
  "All Transactions": "Toutes transactions",
  "Book an Appointment for Salon, Spa & Barber": "Prendre rendez-vous pour un salon, un spa et un barbier",
  "Connect with Google": "Connectez-vous avec Google",
  "Connect with Facebook": "Connectez-vous avec Facebook",
  "Already have an account?": "Vous avez déjà un compte ?",
  "Please wait": "S'il vous plaît, attendez",
  "All fields are required": "Tous les champs sont obligatoires",
  "Card Information Saved": "Informations sur la carte enregistrées",
  "Please add comments": "Veuillez ajouter des commentaires",
  "Review Saved": "Avis enregistré",
  "Others": "Autres",
  "item remove successfully": "l'élément a été supprimé avec succès",
  "NA": "N / A",
  "COD": "MORUE",
  "Stripe": "Bande",
  "PayPal": "PayPal",
  "Paytm": "Paiement",
  "Razorpay": "Razorpay",
  "Instamojo": "Instamojo",
  "Paystack": "Paie",
  "Flutterwave": "Flutterwave",
  "Accepted": "Accepté",
  "Rejected by Freelancer": "Rejeté par Freelancer",
  "Ongoing": "En cours",
  "Completed": "Complété",
  "Cancelled": "Annulé",
  "Refunded": "Remboursé",
  "Delayed": "Retardé",
  "Panding Payment": "Paiement en attente",
  "Status Updated": "Statut mis à jour",
  "Rate Your Appointment": "Évaluez votre rendez-vous",
  "Owner": "Propriétaire",
  "Could not launch": "Impossible de lancer",
  "Choose": "Choisir",
  "Featching Location": "Récupérer un emplacement",
  "The product arrived too late": "Le produit est arrivé trop tard",
  "The product did not match the description": "Le produit ne correspond pas à la description",
  "The purchase was fraudulent": "L'achat était frauduleux",
  "The product was damaged or defective": "Le produit était endommagé ou défectueux",
  "The merchant shipped the wrong item": "Le commerçant a expédié le mauvais article",
  "Wrong Item Size or Wrong Product Shipped": "Mauvaise taille d'article ou mauvais produit expédié",
  "Driver arrived too late": "Le chauffeur est arrivé trop tard",
  "Driver behavior": "Comportement du conducteur",
  "Freelancer behavior": "Comportement Freelancer",
  "Issue with Payment Amount": "Problème avec le montant du paiement",
  "Freelancer was fraudulent": "Le freelance était frauduleux",
  "Related to service": "Lié au service",
  "Satisfaction of services": "Satisfaction des prestations",
  "Choose Issue With": "Choisissez le problème avec",
  "Choose Reason": "Choisissez la raison",
  "Choose Service": "Choisissez le service",
  "Choose Package": "Choisir le forfait",
  "Choose Product": "Choisir un produit",
  "Complaints registered": "Plaintes enregistrées",
  "New Mail Request Received": "Nouvelle demande de courrier reçue",
  "You have received new mail": "Vous avez reçu un nouveau courrier",
  "New Contact Details": "Nouvelles coordonnées",
  "We have received your request, we will respond on your issue soon": "Nous avons reçu votre demande, nous répondrons bientôt à votre problème",
  "Alert!": "Alerte!",
  "Contact Information Sent": "Coordonnées envoyées",
  "Okay": "D'accord",
  "Location services are disabled": "Les services de localisation sont désactivés",
  "Location permissions are permanently denied, we cannot request permissions": "Les autorisations de localisation sont définitivement refusées, nous ne pouvons pas demander d'autorisations",
  "We already have product with other freelancer": "Nous avons déjà des produits avec d'autres freelances",
  "We already have service or package with other salon or with freelancer": "Nous avons déjà un service ou un forfait avec un autre salon ou avec un freelance",
  "Sorry we deliver the order near to": "Désolé, nous livrons la commande près de",
  "Appointments once placed cannot be cancelled and non-refundable": "Les rendez-vous une fois pris ne sont ni annulables ni remboursables",
  "Are you sure": "Es-tu sûr",
  "Thank You!": "Merci!",
  "For Your Appointment": "Pour votre rendez-vous",
  "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout:": "C'est un fait bien établi qu'un lecteur sera distrait par le contenu lisible d'une page en examinant sa mise en page :",
  "\"\"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout\"\",": "\"\"C'est un fait bien établi qu'un lecteur sera distrait par le contenu lisible d'une page en examinant sa mise en page\"\",",
  "TRACK MY APPOINTMENT": "SUIVRE MON RENDEZ-VOUS",
  "BACK TO HOME": "Retour au Menu",
  "Sunday": "Dimanche",
  "Monday": "Lundi",
  "Tuesday": "Mardi",
  "Wednesday": "Mercredi",
  "Thursday": "Jeudi",
  "Friday": "Vendredi",
  "Saturday": "Samedi",
  "Please select Slots": "Veuillez sélectionner les emplacements",
  "Email is not valid": "L'e-mail n'est pas valide",
  "Access denied": "Accès refusé",
  "error": "erreur",
  "Phone Number is required": "Un numéro de téléphone est requis",
  "Something went wrong while signup": "Quelque chose s'est mal passé lors de l'inscription",
  "Something went wrong": "Quelque chose s'est mal passé",
  "Verification": "Vérification",
  "We have sent verification code on": "Nous avons envoyé le code de vérification",
  "Verify": "Vérifier",
  "Successfully Added": "Ajouté avec succès",
  "Successfully Updated": "Mise à jour avec succès",
  "Please select payment method": "Veuillez sélectionner le mode de paiement",
  "We have already select product with other freelancer": "Nous avons déjà sélectionné des produits avec d'autres freelances",
  "Share with buddies": "Partager avec des amis",
  "Copied to clipboard": "Copié dans le presse-papiers",
  "Hey Buddy download": "Hey ma reine, télécharge",
  "Your friend": "Ton ami",
  "has invited you to": "vous a invité",
  "from app store and use my code": "depuis l'App Store et utilise mon code",
  "while sign up we both will get": "En nous inscrivant, nous aurons tous les deux",
  "wallet amount": "montant du portefeuille",
  "Password mismatch": "Incompatibilité de mot de passe",
  "No Website Found": "Aucun site Web trouvé",
  "Please checkout this salon": "Veuillez consulter ce salon",
  "Share with": "Partager avec",
  "Please select specialist": "Veuillez sélectionner une spécialiste",
  "Yes, Place Order": "Oui, passez commande",
  "Please select card": "Veuillez sélectionner la carte",
  "Creating Order": "Créer de l'ordre",
  "TRACK MY ORDERS": "SUIVRE MES COMMANDES",
  "For Your Orders": "Pour vos commandes",
  "Order notes..": "Notes de commande.."
},

"es_DE": {
          "Profile": "Perfil",
          "Inbox": "Bandeja de entrada",
          "Opps, Please Login or Register first!": "Opps, ¡inicie sesión o regístrese primero!",
          "Acount": "Cuenta",
          "Sign In / Sign Up": "Iniciar sesión, crear cuenta",
          "Edit Profile": "Editar perfil",
          "Product Order": "Orden de producto",
          "Your Address": "Su dirección",
          "Wallet": "Cartera",
          "Refer & Earn": "Referir y ganar",
          "Change Password": "Cambia la contraseña",
          "Languages": "Lengua",
          "Chats": "Chatas",
          "Contact Us": "Contáctenos",
          "Frequently Asked Questions": "Preguntas frecuentes",
          "Help": "Ayuda",
          "Privacy Policy": "Política de privacidad",
          "Terms & Conditions": "Términos y condiciones",
          "About us": "Sobre nosotros",
          "About": "Sobre",
          "Logout": "Cerrar sesión",
          "Add New Card": "Agregar nueva tarjeta",
          "Email Address": "Dirección de correo electrónico",
          "Card Holder Name": "Nombre del titular de la tarjeta",
          "Card Number": "Número de tarjeta",
          "CVV": "CVV",
          "MM/YY": "Mm/yy",
          "ADD CARD": "AGREGAR TARJETA",
          "Add Review to": "Agregar revisión a",
          "Please rate the quality of service for the appointment you have got!": "¡Califique la calidad del servicio para la cita que tiene!",
          "Your comments and suggesstions help us improve the service quality better!": "¡Sus comentarios y sugerencias nos ayudan a mejorar mejor la calidad del servicio!",
          "Write Notes": "Escribe notas",
          "Add Review": "Agregar una opinión",
          "Save": "Ahorrar",
          "Cancle": "Atacar",
          "Select Address": "Seleccionar dirección",
          "Add Address": "Añadir dirección",
          "Address": "Dirección",
          "Add New": "Agregar nuevo",
          "All Categories": "todas las categorias",
          "Appointment Detail": "Detalle de la cita",
          "Booking Date & Time": "Fecha de reserva y hora",
          "Booking Date": "Fecha para registrarse",
          "Booking Time": "Tiempo de reserva",
          "Services": "Servicios",
          "Packages": "Paquetes",
          "Pricing": "Fijación",
          "Discount": "Descuento",
          "Wallet Discount": "Descuento de billetera",
          "Distance Cost": "Costo de distancia",
          "Service Tax": "Impuesto de servicio",
          "Total": "Total",
          "Payment Method": "Método de pago",
          "Total Amount": "Cantidad total",
          "Your Appoinments Status": "El estado de su recopilación",
          "Cancel": "Cancelar",
          "Appointments History": "Historial de citas",
          "New": "Nueva",
          "Old": "Antigua",
          "Grand Total": "Gran total",
          "Appointment at": "Cita con",
          "No New Appointment Found!": "¡No se encontró una nueva cita!",
          "No Past Appointment Found!": "¡No se encontró una cita pasada!",
          "Cart": "Carro",
          "Continue": "Continuar",
          "Special Discount": "Descuento especial",
          "OFF": "APAGADA",
          "Total Price": "Precio total",
          "Specialist": "Especialista",
          "Salon": "Salón",
          "and more": "y más",
          "No Data Found Near You!": "¡No se encuentran datos cerca de usted!",
          "Categories": "Categorías",
          "Items": "Elementos",
          "Payments": "Pagos",
          "No Data Found!": "¡Datos no encontrados!",
          "Message...": "Mensaje...",
          "Checkout": "Verificar",
          "min": "mínimo",
          "Bill Details": "Detalles de la factura",
          "item Total": "total",
          "Taxes & Charges": "Impuestos y cargos",
          "To Pay": "Pagar",
          "Select Date & Time": "Seleccione Fecha y hora",
          "Access Your": "Acceder a tu",
          "Location": "Ubicación",
          "USE CURRENT LOCATION": "Utilice la ubicación actual",
          "CHOOSE LOCATION": "ELEGIR LA UBICACIÓN",
          "Complaints": "Quejas",
          "Issue With": "Problema con",
          "Freelancer": "Persona de libre dedicación",
          "Select Freelancer": "Seleccione Freelancer",
          "Select product": "Seleccionar producto",
          "Select service": "Seleccione Servicio",
          "Select package": "Seleccionar paquete",
          "Select Reason": "Razón seleccionado",
          "Title": "Título",
          "Brief of your issue": "Breve de su problema",
          "Comments": "Comentario",
          "Write something on issue": "Escribe algo en el tema",
          "Upload Image": "Cargar imagen",
          "Submit": "Enviar",
          "Full Name": "Nombre completo",
          "Message": "Mensaje",
          "Select Coupon": "Seleccionar cupón",
          "Use coupon code": "Usar código de cupón",
          "Valid until": "Válido hasta",
          "Choose From": "Escoge de",
          "camera": "cámara",
          "Camera": "Cámara",
          "gallery": "galería",
          "Gallery": "Galería",
          "First Name": "Primer nombre",
          "Last Name": "Apellido",
          "Gender": "Género",
          "Male": "Masculina",
          "Female": "Femenina",
          "Email": "Correo electrónico",
          "Code": "Código",
          "Phone": "Teléfono",
          "Connection Failed": "La conexión falló",
          "Could not connect to network": "No se pudo conectar a la red",
          "Please check and try again": "Por favor revisa e intenta de nuevo",
          "retry": "rever",
          "Filters": "Filtros",
          "Done": "Hecho",
          "Hairstyle": "Peinada",
          "Mackup": "Mackup",
          "Hair Styling": "Cortes de cabello",
          "Spa": "Spa",
          "Facial Mackup": "Mackup facial",
          "Trim & Saving": "Recorte y guardado",
          "Rating": "Clasificación",
          "4.0 Star": "4.0 estrella",
          "Other": "Otra",
          "Distance": "Distancia",
          "Sort by": "Ordenar por",
          "Most Popular": "Más popular",
          "Cost Low To High": "Costo de bajo a alto",
          "Cost High To Low": "Costo alto a bajo",
          "Price": "Precio",
          "Find Location": "Encontrar ubicacion",
          "Search location": "Ubicación de búsqueda",
          "Use My Current Location": "Utilice mi ubicación actual",
          "Confirm Location": "Confirmar ubicación",
          "Verify your phone number": "verifica tu numero de telefono",
          "success_verified": "exitoso_verificado",
          "Search salon, spa and barber": "Buscar salón, spa y barbero",
          "Find and book best services": "Encontrar y reservar los mejores servicios",
          "Top Categories": "Las principales categorías",
          "View all": "Ver todo",
          "Top Specialist": "Especialista principal",
          "Top Salon": "Salón superior",
          "Book": "Libro",
          "Top Products": "Productos superiores",
          "ADD": "AGREGAR",
          "Book Services": "Servicios de libros",
          "Packages Details": "Detalles de paquetes",
          "Book Now": "Reservar ahora",
          "Remove Package": "Eliminar paquete",
          "Services Included": "Servicios incluidos",
          "Packages Name": "Nombre de los paquetes",
          "Duration": "Duración",
          "Photos": "Fotos",
          "Payment": "Pago",
          "Offers & Benefits": "Ofertas y beneficios",
          "Apply Coupon Code": "Aplicar código de cupón",
          "Coupon Applied": "Cupón aplicado",
          "Available Balance": "Saldo disponible",
          "Notes For Service": "Notas para el servicio",
          "Appoinments notes": "Notas de recopilación",
          "item Discount": "descuento de artículos",
          "Distance Charge": "Carga de distancia",
          "Please Add Your Address": "Agregue su dirección",
          "Pay": "Pagar",
          "Slots": "Ranura",
          "Select Date": "Seleccione fecha",
          "No Slots Found": "No se encontraron espacios",
          "Select Slots": "Seleccionar espacios",
          "Make Payment": "Hacer el pago",
          "Save Todo and Retrun to List": "Guardar TODO y Returar a la lista",
          "Find Barbarshop Nearby !": "¡Encuentra Barbarrop cerca!",
          "Attractive Promotions !": "¡Promociones atractivas!",
          "Professional Specialist !": "Especialista profesional!",
          "Get Specialist at your door steps !": "¡Obtenga especialista en los escalones de su puerta!",
          "Buy from trusted professional !": "¡Compre en un profesional de confianza!",
          "Skip": "Saltar",
          "Next": "Próxima",
          "Previous": "Anterior",
          "Get Started": "Empezar",
          "English": "Inglesa",
          "Hindi": "hindi",
          "Spanish": "Española",
          "Password": "Clave",
          "Forgot Password ?": "Has olvidado tu contraseña ?",
          "Log In": "Iniciar sesión",
          "Don\"t have account ?": "¿No tienes cuenta?",
          "Sign Up": "Inscribirse",
          "Mobile Number": "Número de teléfono móvil",
          "Add New Address": "Agregar nueva dirección",
          "House / Flat No.": "Casa / piso No.",
          "Landmark": "Punto de referencia",
          "Pincode": "Código PIN",
          "Save Address": "Guardar la dirección",
          "Home": "Hogar",
          "Work": "Trabajar",
          "Update": "Actualizar",
          "Service at": "Servicio",
          "At Home": "En casa",
          "At Salon": "En salón",
          "Order Detail": "Detalle de la orden",
          "Order At": "Ordenar a",
          "Orders": "Pedidos",
          "X": "X",
          "Your Order Status": "El estado de su pedido",
          "Order History": "Historial de pedidos",
          "Order Id": "Solicitar ID",
          "No New Orders Found!": "¡No se encontraron nuevos pedidos!",
          "No Past Orders Found!": "¡No se encontraron órdenes pasadas!",
          "Add Notes": "Agregar notas",
          "Appoinments notes..": "Notas de apopuladores ..",
          "Pay With Stripe": "Pagar con rayas",
          "Expiry": "Expiración",
          "Products Details": "Detalles de productos",
          "Add To Cart": "Añadir al carrito",
          "Sold By": "Vendido por",
          "Categories Info": "Información de categorías",
          "Sub Categories Info": "Información de subcategas",
          "Descriptions": "Descripciones",
          "Special Price": "Precio especial",
          "Off": "Apagada",
          "Only 5 Days Left": "Solo quedan 5 días",
          "Disclaimer": "Descargo de responsabilidad",
          "Related Products": "Productos relacionados",
          "Reviews": "Reseñas",
          "Write your review": "Escribe tu reseña",
          "Leave your experience..": "Deja tu experiencia ..",
          "post": "correo",
          "Kevin Doyle": "Kevin Doyle",
          "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters":
              "Es un hecho establecido desde hace mucho tiempo que un lector se distraerá con el contenido legible de una página al mirar su diseño. El punto de usar lorem ipsum es que tiene una distribución normal más o menos de letras",
          "Products": "Productos",
          "Sort By": "Ordenar por",
          "Invite Now": "Invitar ahora",
          "Create an Account": "Crea una cuenta",
          "Referral Code": "código de referencia",
          "By continuing, you agree to our": "Al continuar, usted acepta nuestro",
          "Terms of Service": "Términos de servicio",
          "You have already account ?": "Ya tienes cuenta?",
          "Reset Password": "Restablecer la contraseña",
          "Enter your email address or phone number and we will send a verification code to generate a new password":
              "Ingrese su dirección de correo electrónico o número de teléfono y enviaremos un código de verificación para generar una nueva contraseña",
          "Send OTP": "Enviar OTP",
          "Generate New Password": "Generar una nueva contraseña",
          "New Password": "Nueva contraseña",
          "Confirm Password": "Confirmar contraseña",
          "Update Password": "Actualiza contraseña",
          "Your Location": "Tu ubicación",
          "Search For Salon, Services.....": "Buscar salón, servicios .....",
          "Salons": "Salón",
          "KM": "Km",
          "OPEN": "ABIERTA",
          "Website": "Sitio web",
          "Call": "Llamar",
          "Chat": "Charlar",
          "Direction": "Dirección",
          "Share": "Cuota",
          "Salon Specialist": "Especialista en salón",
          "Opening Hour": "Hora de apertura",
          "Get Direction": "Obtener una dirección",
          "Type": "Escribe",
          "View": "Vista",
          "Appointment": "Cita",
          "Select Specialist": "Seleccionar especialista",
          "Portfolio": "portafolio",
          "Basic Info": "Información básica",
          "No Internet Connection": "Sin conexión a Internet",
          "Developed By": "Desarrollado por",
          "NearBy": "Cercana",
          "Shop": "Comercio",
          "Appoinment": "Componente",
          "Account": "Cuenta",
          "Top Packages & Offers": "PAQUETES Y OFERTAS TOP",
          "Ms.Jolly Jonthon": "Ms.Jolly Jonthon",
          "Aromatherapy": "Aromaterapia",
          "Fee start from": "CARRACIÓN DE LA TAREDAD DE",
          "All Transactions": "Todas las transacciones",
          "Book an Appointment for Salon, Spa & Barber": "Reserve una cita para Salon, Spa y Barber",
          "Connect with Google": "Conéctese con Google",
          "Connect with Facebook": "Conéctate con Facebook",
          "Already have an account?": "¿Ya tienes una cuenta?",
          "Please wait": "Espere por favor",
          "All fields are required": "Todos los campos son obligatorios",
          "Card Information Saved": "Información de la tarjeta guardada",
          "Please add comments": "Por favor agregue comentarios",
          "Review Saved": "Revisión guardada",
          "Others": "Otras",
          "item remove successfully": "Elemento elimina con éxito",
          "NA": "N / A",
          "COD": "BACALAO",
          "Stripe": "Raya",
          "PayPal": "Paypal",
          "Paytm": "Paytm",
          "Razorpay": "Razonpay",
          "Instamojo": "Instamos",
          "Paystack": "Paystack",
          "Flutterwave": "Flutero",
          "Accepted": "Aceptada",
          "Rejected by Freelancer": "Rechazado por Freelancer",
          "Ongoing": "En curso",
          "Completed": "Terminada",
          "Cancelled": "Cancelada",
          "Refunded": "Reintegrada",
          "Delayed": "Demorada",
          "Panding Payment": "Pago",
          "Status Updated": "Estado actualizado",
          "Rate Your Appointment": "Califica tu cita",
          "Owner": "Dueña",
          "Could not launch": "No pudo lanzar",
          "Choose": "Elegir",
          "Featching Location": "Ubicación de featching",
          "The product arrived too late": "El producto llegó demasiado tarde",
          "The product did not match the description": "El producto no coincidía con la descripción",
          "The purchase was fraudulent": "La compra fue fraudulenta",
          "The product was damaged or defective": "El producto fue dañado o defectuoso",
          "The merchant shipped the wrong item": "El comerciante envió el artículo equivocado",
          "Wrong Item Size or Wrong Product Shipped": "Tamaño de artículo incorrecto o producto incorrecto enviado",
          "Driver arrived too late": "El conductor llegó demasiado tarde",
          "Driver behavior": "Comportamiento del conductor",
          "Freelacer behavior": "Comportamiento libre",
          "Issue with Payment Amount": "Problema con el monto del pago",
          "Freelancer was fraudulent": "Freelancer fue fraudulento",
          "Related to service": "Relacionado con el servicio",
          "Satisfaction of services": "Satisfacción de los servicios",
          "Choose Issue With": "Elija el problema con",
          "Choose Reason": "Elige la razón",
          "Choose Service": "Elija Servicio",
          "Choose Package": "Elija el paquete",
          "Choose Product": "Elija el producto",
          "Complaints registered": "Quejas registradas",
          "New Mail Request Received": "Nueva solicitud de correo recibida",
          "You have received new mail": "Has recibido un nuevo correo",
          "New Contact Details": "Nuevos datos de contacto",
          "We have received your request, we will respond on your issue soon": "Hemos recibido su solicitud, pronto responderemos sobre su problema.",
          "Alert!": "¡Alerta!",
          "Contact Information Sent": "Información de contacto enviada",
          "Okay": "De acuerdo",
          "Location services are disabled": "Los servicios de ubicación están deshabilitados",
          "Location permissions are permanently denied, we cannot request permissions": "Los permisos de ubicación se denegan permanentemente, no podemos solicitar permisos",
          "We already have product with other freelancer": "Ya tenemos producto con otro profesional independiente",
          "We already have service or package with other salon or with freelancer": "Ya tenemos servicio o paquete con otro salón o con Freelancer",
          "Sorry we deliver the order near to": "Lo siento, entregamos el pedido cerca de",
          "Appoinments once placed cannot be cancelled and non-refundable": "Las composiciones una vez colocadas no se pueden cancelar y no se pueden reembolsar",
          "Are you sure": "Está seguro",
          "Thank You!": "¡Gracias!",
          "For Your Appoinment": "Para tu cita",
          "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout":
              "Es un hecho establecido desde hace mucho tiempo que un lector se distraerá con el contenido legible de una página al mirar su diseño",
          "TRACK MY APPOINTMENT": "Rastrear mi cita",
          "BACK TO HOME": "DE VUELTA A CASA",
          "Sunday": "Domingo",
          "Monday": "Lunes",
          "Tuesday": "martes",
          "Wednesday": "miércoles",
          "Thursday": "jueves",
          "Friday": "Viernes",
          "Saturday": "sábado",
          "Please select Slots": "Seleccione las ranuras",
          "Email is not valid": "El correo no es válido",
          "Access denied": "Acceso denegado",
          "error": "error",
          "Phone Number is required": "Se requiere número de teléfono",
          "Something went wrong while signup": "Algo salió mal mientras se registra",
          "Something went wrong": "Algo salió mal",
          "Verification": "Verificación",
          "We have sent verification code on": "Hemos enviado código de verificación en",
          "Verify": "Verificar",
          "Successfully Added": "Agregado exitosamente",
          "Successfully Updated": "Actualizado exitosamente",
          "Please select payment method": "Seleccione el método de pago",
          "We have already select product with other freelancer": "Ya tenemos un producto seleccionado con otro freelancer",
          "Share with buddies": "Compartir con amigos",
          "Copied to clipboard": "Copiado al portapapeles",
          "Hey Buddy download": "Hey Buddy Descargar",
          "Your friend": "Tu amigo",
          "has invited you to": "te ha invitado a",
          "from app store and use my code": "Desde App Store y use mi código",
          "while sign up we both will get": "Mientras se registren, ambos obtendremos",
          "wallet amount": "cantidad de billetera",
          "Password mismatch": "Contraseña no coincide",
          "No Website Found": "No se encuentra el sitio web",
          "Please checkout this salon": "Por favor, consulte este salón",
          "Share with": "Compartir con",
          "Please select specialist": "Seleccione especialista",
          "Yes, Place Order": "Si, coloque el pedido",
          "Please select card": "Seleccione la tarjeta",
          "Creating Order": "Creación de pedidos",
          "TRACK MY ORDERS": "SEGUIMIENTO DE MIS PEDIDOS",
          "For Your Orders": "Para tus pedidos",
          "Order notes..": "Pedidos.."
        },
        "ar_AE": {
          "Profile": "الملف الشخصي",
          "Inbox": "صندوق الوارد",
          "Opps, Please Login or Register first!": "OPPS ، يرجى تسجيل الدخول أو التسجيل أولا!",
          "Acount": "تدفق",
          "Sign In / Sign Up": "تسجيل الدخول / التسجيل",
          "Edit Profile": "تعديل الملف الشخصي",
          "Product Order": "طلبيه",
          "Your Address": "عنوانك",
          "Wallet": "محفظة",
          "Refer & Earn": "الرجوع والكسب",
          "Change Password": "غير كلمة السر",
          "Languages": "اللغات",
          "Chats": "الدردشات",
          "Contact Us": "اتصل بنا",
          "Frequently Asked Questions": "أسئلة مكررة",
          "Help": "مساعدة",
          "Privacy Policy": "سياسة الخصوصية",
          "Terms & Conditions": "البنود و الظروف",
          "About us": "معلومات عنا",
          "About": "حول",
          "Logout": "تسجيل خروج",
          "Add New Card": "أضف بطاقة جديدة",
          "Email Address": "عنوان البريد الالكترونى",
          "Card Holder Name": "إسم صاحب البطاقة",
          "Card Number": "رقم البطاقة",
          "CVV": "CVV",
          "MM/YY": "مم/يي",
          "ADD CARD": "إضافة بطاقة",
          "Add Review to": "أضف مراجعة إلى",
          "Please rate the quality of service for the appointment you have got!": "يرجى تقييم جودة الخدمة لهذا الموعد الذي حصلت عليه!",
          "Your comments and suggesstions help us improve the service quality better!": "تساعدنا تعليقاتك واقتراحاتك على تحسين جودة الخدمة بشكل أفضل!",
          "Write Notes": "اكتب الملاحظات",
          "Add Review": "إضافة مراجعة",
          "Save": "يحفظ",
          "Cancle": "Cancle",
          "Select Address": "حدد العنوان",
          "Add Address": "اضف عنوان",
          "Address": "تبوك",
          "Add New": "اضف جديد",
          "All Categories": "جميع الفئات",
          "Appointment Detail": "تفاصيل الموعد",
          "Booking Date & Time": "تاريخ الحجز والوقت",
          "Booking Date": "تاريخ الحجز",
          "Booking Time": "وقت الحجز",
          "Services": "خدمات",
          "Packages": "حزم",
          "Pricing": "التسعير",
          "Discount": "تخفيض",
          "Wallet Discount": "خصم محفظة",
          "Distance Cost": "تكلفة المسافة",
          "Service Tax": "ضريبة الخدمة",
          "Total": "المجموع",
          "Payment Method": "طريقة الدفع او السداد",
          "Total Amount": "المبلغ الإجمالي",
          "Your Appoinments Status": "حالة appoinments الخاصة بك",
          "Cancel": "يلغي",
          "Appointments History": "تاريخ المواعيد",
          "New": "جديد",
          "Old": "قديم",
          "Grand Total": "المبلغ الإجمالي",
          "Appointment at": "موعد في",
          "No New Appointment Found!": "لم يتم العثور على موعد جديد!",
          "No Past Appointment Found!": "لم يتم العثور على موعد سابق!",
          "Cart": "عربة التسوق",
          "Continue": "يكمل",
          "Special Discount": "خصم خاص",
          "OFF": "إيقاف",
          "Total Price": "السعر الكلي",
          "Specialist": "متخصص",
          "Salon": "صالون",
          "and more": "و اكثر",
          "No Data Found Near You!": "لم يتم العثور على بيانات بالقرب منك!",
          "Categories": "فئات",
          "Items": "العناصر",
          "Payments": "المدفوعات",
          "No Data Found!": "لاتوجد بيانات!",
          "Message...": "رسالة...",
          "Checkout": "الدفع",
          "min": "دقيقة",
          "Bill Details": "تفاصيل فاتورة",
          "item Total": "مجموع الاشياء",
          "Taxes & Charges": "الضرائب والرسوم",
          "To Pay": "لدفع",
          "Select Date & Time": "حدد التاريخ والوقت",
          "Access Your": "الوصول إلى الخاص بك",
          "Location": "موقع",
          "USE CURRENT LOCATION": "استخدام الموقع الحالي",
          "CHOOSE LOCATION": "اختيار موقع",
          "Complaints": "شكاوي",
          "Issue With": "القضية مع",
          "Freelancer": "مستقل",
          "Select Freelancer": "حدد Freelancer",
          "Select product": "حدد المنتج",
          "Select service": "حدد الخدمة",
          "Select package": "حدد الحزمة",
          "Select Reason": "حدد السبب",
          "Title": "عنوان",
          "Brief of your issue": "موجز من مشكلتك",
          "Comments": "تعليقات",
          "Write something on issue": "اكتب شيئًا في القضية",
          "Upload Image": "تحميل الصور",
          "Submit": "يُقدِّم",
          "Full Name": "الاسم الكامل",
          "Message": "رسالة",
          "Select Coupon": "حدد القسيمة",
          "Use coupon code": "استخدم رمز القسيمة",
          "Valid until": "صالح حتى",
          "Choose From": "اختر من",
          "camera": "كاميرا",
          "Camera": "آلة تصوير",
          "gallery": "صالة عرض",
          "Gallery": "صالة عرض",
          "First Name": "الاسم الاول",
          "Last Name": "الكنية",
          "Gender": "جنس",
          "Male": "ذكر",
          "Female": "أنثى",
          "Email": "البريد الإلكتروني",
          "Code": "شفرة",
          "Phone": "هاتف",
          "Connection Failed": "فشل الاتصال",
          "Could not connect to network": "لا يمكن الاتصال بالشبكة",
          "Please check and try again": "يرجى مراجعة وحاول مرة أخرى",
          "retry": "إعادة المحاولة",
          "Filters": "المرشحات",
          "Done": "فعله",
          "Hairstyle": "تسريحه شعر",
          "Mackup": "ماك يصل",
          "Hair Styling": "تسريحة شعر",
          "Spa": "منتجع صحي",
          "Facial Mackup": "الوجه mackup",
          "Trim & Saving": "تقليم وتوفير",
          "Rating": "تقييم",
          "4.0 Star": "4.0 نجمة",
          "Other": "آخر",
          "Distance": "مسافه: بعد",
          "Sort by": "صنف حسب",
          "Most Popular": "الأكثر شعبية",
          "Cost Low To High": "تكلفة منخفضة إلى عالية",
          "Cost High To Low": "تكلفة عالية إلى منخفضة",
          "Price": "سعر",
          "Find Location": "ابحث عن الموقع",
          "Search location": "موقع البحث",
          "Use My Current Location": "استخدم موقعي الحالي",
          "Confirm Location": "تأكيد الموقع",
          "Verify your phone number": "اكد على رقم هاتفك او جوالك",
          "success_verified": "Success_Verified",
          "Search salon, spa and barber": "ابحث صالون وسبا وحلاقة",
          "Find and book best services": "ابحث عن أفضل الخدمات وحجزها",
          "Top Categories": "الفئات العليا",
          "View all": "عرض الكل",
          "Top Specialist": "كبار المتخصصين",
          "Top Salon": "أعلى صالون",
          "Book": "الكتاب",
          "Top Products": "أفضل المنتجات",
          "ADD": "يضيف",
          "Book Services": "خدمات الكتاب",
          "Packages Details": "تفاصيل الحزم",
          "Book Now": "احجز الآن",
          "Remove Package": "إزالة الحزمة",
          "Services Included": "شملت الخدمات",
          "Packages Name": "اسم الحزم",
          "Duration": "مدة",
          "Photos": "الصور",
          "Payment": "دفع",
          "Offers & Benefits": "العروض والفوائد",
          "Apply Coupon Code": "تطبيق رمز القسيمة",
          "Coupon Applied": "كوبون تطبيق",
          "Available Balance": "الرصيد المتوفر",
          "Notes For Service": "ملاحظات للخدمة",
          "Appoinments notes": "ملاحظات appoinments",
          "item Discount": "خصم البند",
          "Distance Charge": "شحنة المسافة",
          "Please Add Your Address": "الرجاء إضافة عنوانك",
          "Pay": "يدفع",
          "Slots": "فتحات",
          "Select Date": "حدد تاريخ",
          "No Slots Found": "لم يتم العثور على فتحات",
          "Select Slots": "حدد فتحات",
          "Make Payment": "قم بالدفع",
          "Save Todo and Retrun to List": "حفظ TODO واسترج",
          "Find Barbarshop Nearby !": "ابحث عن Barbarshop في مكان قريب!",
          "Attractive Promotions !": "عروض ترويجية جذابة!",
          "Professional Specialist !": "أخصائي محترف!",
          "Get Specialist at your door steps !": "احصل على متخصص في خطوات الباب!",
          "Buy from trusted professional !": "شراء من المهنية الموثوقة!",
          "Skip": "يتخطى",
          "Next": "التالي",
          "Previous": "سابق",
          "Get Started": "البدء",
          "English": "إنجليزي",
          "Hindi": "الهندية",
          "Spanish": "الأسبانية",
          "Password": "كلمة المرور",
          "Forgot Password ?": "هل نسيت كلمة السر ؟",
          "Log In": "تسجيل الدخول",
          "Don\"t have account ?": "هل لديك حساب؟",
          "Sign Up": "اشتراك",
          "Mobile Number": "رقم الهاتف المحمول",
          "Add New Address": "أضف عنوانًا جديدًا",
          "House / Flat No.": "منزل / شقة رقم",
          "Landmark": "معلم معروف",
          "Pincode": "pincode",
          "Save Address": "حفظ العنوان",
          "Home": "مسكن",
          "Work": "عمل",
          "Update": "تحديث",
          "Service at": "الخدمة في",
          "At Home": "فى المنزل",
          "At Salon": "في صالون",
          "Order Detail": "تفاصيل الطلب",
          "Order At": "أمر في",
          "Orders": "الطلب #٪ s",
          "X": "x",
          "Your Order Status": "حالة طلبك",
          "Order History": "تاريخ الطلب",
          "Order Id": "رقم التعريف الخاص بالطلب",
          "No New Orders Found!": "لم يتم العثور على أوامر جديدة!",
          "No Past Orders Found!": "لم يتم العثور على أوامر سابقة!",
          "Add Notes": "أضف ملاحظات",
          "Appoinments notes..": "ملاحظات appoinments ..",
          "Pay With Stripe": "دفع مع شريط",
          "Expiry": "انقضاء",
          "Products Details": "تفاصيل المنتجات",
          "Add To Cart": "أضف إلى السلة",
          "Sold By": "تم بيعها من قبل",
          "Categories Info": "معلومات الفئات",
          "Sub Categories Info": "معلومات الفئات الفرعية",
          "Descriptions": "الأوصاف",
          "Special Price": "سعر خاص",
          "Off": "عن",
          "Only 5 Days Left": "بقي 5 أيام فقط",
          "Disclaimer": "تنصل",
          "Related Products": "منتجات ذات صله",
          "Reviews": "المراجعات",
          "Write your review": "اكتب مراجعتك",
          "Leave your experience..": "اترك تجربتك ..",
          "post": "بريد",
          "Kevin Doyle": "كيفن دويل",
          "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters":
              "إنها حقيقة راسخة أن القارئ سوف يصرف انتباهه عن طريق المحتوى القابل للقراءة للصفحة عند النظر إلى تخطيطه. الهدف من استخدام lorem ipsum هو أنه يحتوي على توزيع طبيعي أكثر أو أقل من الحروف",
          "Products": "منتجات",
          "Sort By": "صنف حسب",
          "Invite Now": "دعوة الآن",
          "Create an Account": "انشئ حساب",
          "Referral Code": "كود الإحالة",
          "By continuing, you agree to our": "من خلال الاستمرار ، أنت توافق على",
          "Terms of Service": "شروط الخدمة",
          "You have already account ?": "لديك حساب بالفعل؟",
          "Reset Password": "إعادة تعيين كلمة المرور",
          "Enter your email address or phone number and we will send a verification code to generate a new password": "أدخل عنوان بريدك الإلكتروني أو رقم هاتفك وسنرسل رمز التحقق لإنشاء كلمة مرور جديدة",
          "Send OTP": "إرسال OTP",
          "Generate New Password": "إنشاء كلمة مرور جديدة",
          "New Password": "كلمة السر الجديدة",
          "Confirm Password": "تأكيد كلمة المرور",
          "Update Password": "تطوير كلمة السر",
          "Your Location": "موقعك",
          "Search For Salon, Services.....": "ابحث عن الصالون والخدمات .....",
          "Salons": "صالونات",
          "KM": "كم",
          "OPEN": "افتح",
          "Website": "موقع الكتروني",
          "Call": "مكالمة",
          "Chat": "دردشة",
          "Direction": "اتجاه",
          "Share": "يشارك",
          "Salon Specialist": "أخصائي الصالون",
          "Opening Hour": "ساعة الافتتاح",
          "Get Direction": "احصل على اتجاه",
          "Type": "يكتب",
          "View": "رأي",
          "Appointment": "ميعاد",
          "Select Specialist": "حدد متخصص",
          "Portfolio": "مَلَفّ",
          "Basic Info": "معلومات أساسية",
          "No Internet Connection": "لا يوجد اتصال إنترنت",
          "Developed By": "طورت بواسطة",
          "NearBy": "مجاور",
          "Shop": "محل",
          "Appoinment": "ميعاد",
          "Account": "الحساب",
          "Top Packages & Offers": "أعلى الحزم والعروض",
          "Ms.Jolly Jonthon": "السيدة جولي جونثون",
          "Aromatherapy": "العلاج العطري",
          "Fee start from": "تبدأ الرسوم من",
          "All Transactions": "كل الحركات المالية",
          "Book an Appointment for Salon, Spa & Barber": "حجز موعد للصالون والسبا والحلاق",
          "Connect with Google": "تواصل مع Google",
          "Connect with Facebook": "تواصل مع الفيسبوك",
          "Already have an account?": "هل لديك حساب؟",
          "Please wait": "أرجو الإنتظار",
          "All fields are required": "جميع الحقول مطلوبة",
          "Card Information Saved": "تم حفظ معلومات البطاقة",
          "Please add comments": "الرجاء إضافة تعليقات",
          "Review Saved": "مراجعة حفظ",
          "Others": "آحرون",
          "item remove successfully": "العنصر إزالة بنجاح",
          "NA": "نا",
          "COD": "سمك القد",
          "Stripe": "شريط",
          "PayPal": "PayPal",
          "Paytm": "paytm",
          "Razorpay": "رازورباي",
          "Instamojo": "Instamojo",
          "Paystack": "PayStack",
          "Flutterwave": "Flutterwave",
          "Accepted": "وافقت",
          "Rejected by Freelancer": "رفضه المستقل",
          "Ongoing": "جاري التنفيذ",
          "Completed": "مكتمل",
          "Cancelled": "ألغيت",
          "Refunded": "استرداد",
          "Delayed": "تأخير",
          "Panding Payment": "دفع الدفعة",
          "Status Updated": "تم تحديث الحالة",
          "Rate Your Appointment": "قيم موعدك",
          "Owner": "صاحب",
          "Could not launch": "لا يمكن إطلاق",
          "Choose": "يختار",
          "Featching Location": "موقع رائع",
          "The product arrived too late": "وصل المنتج بعد فوات الأوان",
          "The product did not match the description": "المنتج لا يتطابق مع الوصف",
          "The purchase was fraudulent": "كان عملية الشراء احتيالية",
          "The product was damaged or defective": "كان المنتج تضررًا أو معيبًا",
          "The merchant shipped the wrong item": "قام التاجر بشحن العنصر الخاطئ",
          "Wrong Item Size or Wrong Product Shipped": "حجم عنصر خاطئ أو منتج خاطئ",
          "Driver arrived too late": "وصل السائق بعد فوات الأوان",
          "Driver behavior": "سلوك السائق",
          "Freelacer behavior": "سلوك Freelacer",
          "Issue with Payment Amount": "مشكلة مع مبلغ الدفع",
          "Freelancer was fraudulent": "كان مستقل احتيالي",
          "Related to service": "تتعلق بالخدمة",
          "Satisfaction of services": "رضا الخدمات",
          "Choose Issue With": "اختر مشكلة مع",
          "Choose Reason": "اختر السبب",
          "Choose Service": "اختر الخدمة",
          "Choose Package": "اختر الحزمة",
          "Choose Product": "اختر المنتج",
          "Complaints registered": "الشكاوى المسجلة",
          "New Mail Request Received": "تم استلام طلب البريد الجديد",
          "You have received new mail": "لقد تلقيت بريدًا جديدًا",
          "New Contact Details": "تفاصيل الاتصال الجديدة",
          "We have received your request, we will respond on your issue soon": "لقد تلقينا طلبك ، وسوف نرد على مشكلتك قريبًا",
          "Alert!": "انذار!",
          "Contact Information Sent": "معلومات الاتصال المرسلة",
          "Okay": "تمام",
          "Location services are disabled": "خدمات الموقع معطلة",
          "Location permissions are permanently denied, we cannot request permissions": "يتم رفض أذونات الموقع بشكل دائم ، لا يمكننا طلب أذونات",
          "We already have product with other freelancer": "لدينا بالفعل منتج مع مستقل آخر",
          "We already have service or package with other salon or with freelancer": "لدينا بالفعل خدمة أو حزمة مع صالون آخر أو مع Freelancer",
          "Sorry we deliver the order near to": "آسف نحن نقدم الطلب بالقرب من",
          "Appoinments once placed cannot be cancelled and non-refundable": "لا يمكن إلغاء التوعية بمجرد وضعها وغير قابلة للاسترداد",
          "Are you sure": "هل أنت واثق",
          "Thank You!": "شكرا لك!",
          "For Your Appoinment": "للتنسيق الخاص بك",
          "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout":
              "إنها حقيقة راسخة أن القارئ سوف يصرف انتباهه عن طريق المحتوى القابل للقراءة للصفحة عند النظر إلى تخطيطه",
          "TRACK MY APPOINTMENT": "تتبع موعدي",
          "BACK TO HOME": "العودة إلى المنزل",
          "Sunday": "الأحد",
          "Monday": "الاثنين",
          "Tuesday": "يوم الثلاثاء",
          "Wednesday": "الأربعاء",
          "Thursday": "يوم الخميس",
          "Friday": "جمعة",
          "Saturday": "السبت",
          "Please select Slots": "الرجاء تحديد فتحات",
          "Email is not valid": "البريد الإلكتروني غير صالح",
          "Access denied": "تم الرفض",
          "error": "خطأ",
          "Phone Number is required": "رقم الهاتف مطلوب",
          "Something went wrong while signup": "حدث خطأ ما أثناء الاشتراك",
          "Something went wrong": "هناك خطأ ما",
          "Verification": "تَحَقّق",
          "We have sent verification code on": "لقد أرسلنا رمز التحقق على",
          "Verify": "يؤكد",
          "Successfully Added": "أضيف بنجاح",
          "Successfully Updated": "تم التحديث بنجاح",
          "Please select payment method": "الرجاء تحديد طريقة الدفع",
          "We have already select product with other freelancer": "لقد اخترنا بالفعل منتجًا مع Freelancer الآخر",
          "Share with buddies": "مشاركة مع الأصدقاء",
          "Copied to clipboard": "نسخ إلى الحافظة",
          "Hey Buddy download": "يا صديقي تنزيل",
          "Your friend": "صديقك",
          "has invited you to": "لقد دعتك إلى",
          "from app store and use my code": "من متجر التطبيقات واستخدم الكود الخاص بي",
          "while sign up we both will get": "بينما التسجيل سنحصل على كلانا",
          "wallet amount": "كمية المحفظة",
          "Password mismatch": "عدم تطابق كلمة المرور",
          "No Website Found": "لم يتم العثور على موقع ويب",
          "Please checkout this salon": "يرجى الخروج من هذا الصالون",
          "Share with": "شارك مع",
          "Please select specialist": "الرجاء تحديد أخصائي",
          "Yes, Place Order": "نعم ، ترتيب المكان",
          "Please select card": "الرجاء تحديد بطاقة",
          "Creating Order": "إنشاء ترتيب",
          "TRACK MY ORDERS": "تتبع طلباتي",
          "For Your Orders": "لأوامرك",
          "Order notes..": "ترتيب ملاحظات.."
        },
      };
}
